//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CastroCateringBookingSystem.Admin
{
    public partial class AdminLogin
    {
        protected global::System.Web.UI.WebControls.TextBox txtAdminUsername;
        protected global::System.Web.UI.WebControls.TextBox txtAdminPassword;
        protected global::System.Web.UI.WebControls.Label lblStatus;
        protected global::System.Web.UI.WebControls.Button btnAdminLogin;
    }
}
