//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CastroCateringBookingSystem.Pages
{
    public partial class AdminDatabaseBackup
    {
        protected global::System.Web.UI.WebControls.Label       lblDbSize;
        protected global::System.Web.UI.WebControls.Label       lblLastBackup;
        protected global::System.Web.UI.WebControls.Label       lblTotalRecords;
        protected global::System.Web.UI.WebControls.Label       lblTotalUsers;
        protected global::System.Web.UI.WebControls.Label       lblStatus;
        protected global::System.Web.UI.WebControls.Button      btnBackup;
        protected global::System.Web.UI.WebControls.GridView    gvBackupHistory;
        protected global::System.Web.UI.WebControls.PlaceHolder phNoHistory;
    }
}
