//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CastroCateringBookingSystem.Pages
{
    public partial class Booking
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm bookingForm;

        // ── Form inputs ──
        protected global::System.Web.UI.WebControls.TextBox     txtClientName;
        protected global::System.Web.UI.WebControls.TextBox     txtPhoneNumber;
        protected global::System.Web.UI.WebControls.DropDownList ddlEventType;
        protected global::System.Web.UI.WebControls.TextBox     txtEventDate;
        protected global::System.Web.UI.WebControls.TextBox     txtGuestCount;
        protected global::System.Web.UI.WebControls.DropDownList ddlPaymentMode;
        protected global::System.Web.UI.WebControls.TextBox     txtVenue;
        protected global::System.Web.UI.WebControls.DropDownList ddlVenueLocation;

        // ── JS → server hidden fields ──
        protected global::System.Web.UI.WebControls.HiddenField hfServiceStyle;
        protected global::System.Web.UI.WebControls.HiddenField hfPackageName;
        protected global::System.Web.UI.WebControls.HiddenField hfPackagePrice;
        protected global::System.Web.UI.WebControls.HiddenField hfTotalAmount;

        // ── Server → JS receipt hidden fields ──
        protected global::System.Web.UI.WebControls.HiddenField hfShowReceipt;
        protected global::System.Web.UI.WebControls.HiddenField hfReceiptRef;
        protected global::System.Web.UI.WebControls.HiddenField hfReceiptName;
        protected global::System.Web.UI.WebControls.HiddenField hfReceiptPhone;
        protected global::System.Web.UI.WebControls.HiddenField hfReceiptEvent;
        protected global::System.Web.UI.WebControls.HiddenField hfReceiptDate;
        protected global::System.Web.UI.WebControls.HiddenField hfReceiptVenue;
        protected global::System.Web.UI.WebControls.HiddenField hfReceiptGuests;
        protected global::System.Web.UI.WebControls.HiddenField hfReceiptPkg;
        protected global::System.Web.UI.WebControls.HiddenField hfReceiptPPG;
        protected global::System.Web.UI.WebControls.HiddenField hfReceiptService;
        protected global::System.Web.UI.WebControls.HiddenField hfReceiptPayment;
        protected global::System.Web.UI.WebControls.HiddenField hfReceiptTotal;

        // ── Buttons / labels ──
        protected global::System.Web.UI.WebControls.Label  lblBookingError;
        protected global::System.Web.UI.WebControls.Button btnConfirm;
    }
}
