//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CastroCateringBookingSystem.Pages
{
    public partial class Profile
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        // ── Profile picture ──
        protected global::System.Web.UI.WebControls.Image imgProfilePic;
        protected global::System.Web.UI.WebControls.FileUpload fuProfilePic;

        // ── Display labels ──
        protected global::System.Web.UI.WebControls.Label lblProfileAvatar;
        protected global::System.Web.UI.WebControls.Label lblProfileName;
        protected global::System.Web.UI.WebControls.Label lblProfileEmail;
        protected global::System.Web.UI.WebControls.Label lblInfoUsername;
        protected global::System.Web.UI.WebControls.Label lblInfoEmail;
        protected global::System.Web.UI.WebControls.Label lblInfoPhone;
        protected global::System.Web.UI.WebControls.Label lblInfoAddress;

        // ── Edit form controls ──
        protected global::System.Web.UI.WebControls.TextBox txtEditUsername;
        protected global::System.Web.UI.WebControls.TextBox txtEditEmail;
        protected global::System.Web.UI.WebControls.TextBox txtEditPhone;
        protected global::System.Web.UI.WebControls.TextBox txtEditAddress;
        protected global::System.Web.UI.WebControls.Button btnSaveProfile;
        protected global::System.Web.UI.WebControls.Label lblEditStatus;

        // ── Booking history ──
        protected global::System.Web.UI.WebControls.Label lblBookingCount;
        protected global::System.Web.UI.WebControls.Repeater rptBookings;
        protected global::System.Web.UI.WebControls.PlaceHolder phNoBookings;
    }
}
