//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CastroCateringBookingSystem.Pages
{
    public partial class Profile
    {
        /// <summary>form1 control.</summary>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>lblProfileAvatar — first letter of username.</summary>
        protected global::System.Web.UI.WebControls.Label lblProfileAvatar;

        /// <summary>lblProfileName control.</summary>
        protected global::System.Web.UI.WebControls.Label lblProfileName;

        /// <summary>lblProfileEmail control.</summary>
        protected global::System.Web.UI.WebControls.Label lblProfileEmail;

        /// <summary>lblInfoUsername control.</summary>
        protected global::System.Web.UI.WebControls.Label lblInfoUsername;

        /// <summary>lblInfoEmail control.</summary>
        protected global::System.Web.UI.WebControls.Label lblInfoEmail;

        /// <summary>lblInfoPhone control.</summary>
        protected global::System.Web.UI.WebControls.Label lblInfoPhone;

        /// <summary>lblInfoAddress control.</summary>
        protected global::System.Web.UI.WebControls.Label lblInfoAddress;

        /// <summary>lblBookingCount control.</summary>
        protected global::System.Web.UI.WebControls.Label lblBookingCount;

        /// <summary>rptBookings — booking history repeater.</summary>
        protected global::System.Web.UI.WebControls.Repeater rptBookings;

        /// <summary>phNoBookings — shown when user has no bookings.</summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phNoBookings;
    }
}
